"""empty message

Revision ID: 560711fda07f
Revises: 1e0554c857ce
Create Date: 2025-12-06 17:36:35.808830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560711fda07f'
down_revision = '1e0554c857ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    product_columns = {col['name'] for col in inspector.get_columns('product')}
    with op.batch_alter_table('product', schema=None) as batch_op:
        if 'condition' not in product_columns:
            batch_op.add_column(sa.Column('condition', sa.String(length=10), nullable=True))
        if 'region' not in product_columns:
            batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        if 'city' not in product_columns:
            batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        if 'delivery' not in product_columns:
            batch_op.add_column(sa.Column('delivery', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    product_columns = {col['name'] for col in inspector.get_columns('product')}
    with op.batch_alter_table('product', schema=None) as batch_op:
        if 'delivery' in product_columns:
            batch_op.drop_column('delivery')
        if 'city' in product_columns:
            batch_op.drop_column('city')
        if 'region' in product_columns:
            batch_op.drop_column('region')
        if 'condition' in product_columns:
            batch_op.drop_column('condition')

    # ### end Alembic commands ###
