"""add message attachments

Revision ID: b7e2c4d1a9f0
Revises: 8a7b461332ff
Create Date: 2026-01-31 19:11:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e2c4d1a9f0'
down_revision = '8a7b461332ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_original_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_mime', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('attachment_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('attachment_size')
        batch_op.drop_column('attachment_mime')
        batch_op.drop_column('attachment_original_name')
        batch_op.drop_column('attachment_filename')

    # ### end Alembic commands ###
