"""Add image field to Category model

Revision ID: f4c2fd5f47f1
Revises: 560711fda07f
Create Date: 2025-12-12 16:36:00.779537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'f4c2fd5f47f1'
down_revision = '560711fda07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование индексов перед удалением через SQL
    connection = op.get_bind()
    
    # Список индексов для проверки
    indexes_to_check = [
        'idx_review_buyer_id',
        'idx_review_created_at', 
        'idx_review_product_id',
        'idx_review_seller_id'
    ]
    
    for index_name in indexes_to_check:
        # Проверяем существование индекса
        result = connection.execute(
            text("SELECT COUNT(*) FROM pg_indexes WHERE tablename = 'review' AND indexname = :index_name"),
            {'index_name': index_name}
        )
        exists = result.scalar() > 0
        
        if exists:
            # Удаляем индекс только если он существует
            connection.execute(text(f"DROP INDEX IF EXISTS {index_name}"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_review_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_review_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_review_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_review_buyer_id'), ['buyer_id'], unique=False)

    # ### end Alembic commands ###
