"""Add image field to Category model

Revision ID: f4c2fd5f47f1
Revises: 560711fda07f
Create Date: 2025-12-12 16:36:00.779537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c2fd5f47f1'
down_revision = '560711fda07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_review_buyer_id'))
        batch_op.drop_index(batch_op.f('idx_review_created_at'))
        batch_op.drop_index(batch_op.f('idx_review_product_id'))
        batch_op.drop_index(batch_op.f('idx_review_seller_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_review_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_review_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_review_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_review_buyer_id'), ['buyer_id'], unique=False)

    # ### end Alembic commands ###
